const ADMIN = 'ADMIN';
const OWNER = 'OWNER';
const EMPLOYEE = 'EMPLOYEE';
const CUSTOMER = 'CUSTOMER';
const SUPERADMIN = 'SUPERADMIN';

module.exports = {
  ADMIN: ADMIN,
  OWNER: OWNER,
  EMPLOYEE: EMPLOYEE,
  CUSTOMER: CUSTOMER,
  SUPERADMIN: SUPERADMIN,
};
